version : '3.8'

services:

  yqefast-nacos:

    container_name: pet-nacos

    image: nacos/nacos-server:latest

    environment:

      - MODE=standalone

      - SPRING_DATASOURCE_PLATFORM=mysql

      - MYSQL_SERVICE_HOST=47.92.149.249

      - MYSQL_SERVICE_DB_NAME=yqe-fast-nacos

      - MYSQL_SERVICE_USER=root

      - MYSQL_SERVICE_PASSWORD=hash@1234

    volumes:

      - /mnt/nacos/standalone-logs/:/home/nacos/logs

      - ./custom.properties:/home/nacos/conf/application.properties

   ##  - /mnt/nacos/conf/application.properties:/home/nacos/conf/application.properties

    ports:

      - "8848:8848"

      - "9848:9848"

      - "9849:9849"

    restart: always

