# Tomcat
server:
  port: 9209

# Spring
spring:
  application:
    # 应用名称
    name: pet-xxl-executor
  profiles:
    # 环境配置
    active: @profiles.active@
  # nacos 配置
  cloud:
    nacos:
      # nacos 服务地址
      server-addr: @nacos.server@
      discovery:
        # 注册组
        group: @nacos.discovery.group@
        namespace: ${spring.profiles.active}
      config:
        # 配置组
        group: @nacos.config.group@
        namespace: ${spring.profiles.active}
  config:
    import:
      - optional:nacos:application-common.yml
      - optional:nacos:datasource.yml
      - optional:nacos:${spring.application.name}.yml


#spring.main.web-environment=false
# log config
logging.config: classpath:logback.xml

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses: pet-xxl-admin
jasypt.encryptor.password: samples
xxl.job.executor.logpath: /logs/xxl-job-exector/
xxl.job.executor.logretentiondays: 30
xxl.job.accessToken:
